In [4]:
CUDA_VISIBLE_DEVICES=0
import tensorflow as tf

In [15]:
rank12 = tf.Variable(["test","ok"],tf.string)
rank23 = tf.Variable([[["test","ok"],["fuck","shit"]],[["test","no"],["fuck","shit"]]],tf.string)

In [6]:
tf.shape(rank23)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2], dtype=int32)>

In [35]:
tf.shape(rank12)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

In [8]:
tensor1 = tf.ones([1,2,3])

In [9]:
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [10]:
tensor2 = tf.reshape(tensor1,[2,3,1])

In [11]:
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [12]:
tensor3 = tf.reshape(tensor2,[3, -1])

In [13]:
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [54]:
tf.shape(tensor1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [55]:
tf.shape(tensor2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 1], dtype=int32)>

In [56]:
tf.shape(tensor3)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [57]:
print(rank23)

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=string, numpy=
array([[[b'test', b'ok'],
        [b'fuck', b'shit']],

       [[b'test', b'no'],
        [b'fuck', b'shit']]], dtype=object)>


In [58]:
tensor23 = tf.reshape(rank23,[-1])

In [59]:
print(tensor23)

tf.Tensor([b'test' b'ok' b'fuck' b'shit' b'test' b'no' b'fuck' b'shit'], shape=(8,), dtype=string)


In [17]:
tensor231 = tf.reshape(rank23,[4,-1])

In [18]:
print(tensor231)

tf.Tensor(
[[b'test' b'ok']
 [b'fuck' b'shit']
 [b'test' b'no']
 [b'fuck' b'shit']], shape=(4, 2), dtype=string)


In [12]:
tensor231 = tf.reshape(rank23,[4,2])

In [37]:
print(tensor231)

tf.Tensor(
[[b'test']
 [b'ok']
 [b'fuck']
 [b'shit']
 [b'test']
 [b'no']
 [b'fuck']
 [b'shit']], shape=(8, 1), dtype=string)


In [35]:
tensor231 = tf.reshape(rank23,[8,1])

In [38]:
t = tf.zeros([4,4,4,4])

In [49]:
t = tf.reshape(t,[16,16])
print(t)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(16, 16), dtype=float32)


In [52]:
import matplotlib.pyplot as plt 
import numpy as np 

In [53]:
plt.plot(x,y,'ro')
plt.axis([0,6,0,20])
plt.plot(np.unique(x), np.poly1d(np.polyfit(x,y,1))(np.unique(x)))
plt.show()

NameError: name 'x' is not defined